"""Viral share artifact — export context cards as markdown or self-contained HTML."""

from __future__ import annotations

import re
import time
from datetime import datetime
from typing import Any, Dict, List, Optional


# ── Redaction helpers ─────────────────────────────────────────────────────────

_PII_PATTERNS = [
    (r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b", "[EMAIL]"),
    (r"\b\d{3}[-.]?\d{3}[-.]?\d{4}\b", "[PHONE]"),
    (r"\b\d{3}-\d{2}-\d{4}\b", "[SSN]"),
]

_NAME_PATTERN = re.compile(r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)\b")

_NUMBER_PATTERN = re.compile(r"\b\d[\d,.]*\b")


def _apply_redaction(text: str, preset: str | None) -> str:
    if not preset or not text:
        return text
    if preset == "pii":
        for pattern, replacement in _PII_PATTERNS:
            text = re.sub(pattern, replacement, text)
    elif preset == "names":
        text = _NAME_PATTERN.sub("[NAME]", text)
    elif preset == "numbers":
        text = _NUMBER_PATTERN.sub("[NUM]", text)
    return text


# ── Card renderers ────────────────────────────────────────────────────────────

def _render_markdown(query: str, pack, beliefs: Dict, redact: str | None) -> str:
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    r = _apply_redaction

    lines = [
        f"# 🧠 Memory Card: {r(query, redact)}",
        f"_Generated by Synapse AI Memory — {date_str}_",
        "",
        "## Context",
        r(pack.summary or "(no summary)", redact),
        "",
        "## Key Facts",
    ]

    memories = getattr(pack, "memories", []) or []
    if memories:
        for mem in memories:
            content = mem.get("content", "") if isinstance(mem, dict) else getattr(mem, "content", str(mem))
            lines.append(f"- {r(content, redact)}")
    else:
        lines.append("- (no memories)")

    lines.extend(["", "## Evidence Chain"])
    provenance = getattr(pack, "provenance", []) or []
    if provenance:
        for entry in provenance:
            lines.append(f"- {r(str(entry), redact)}")
    else:
        lines.append("- (no provenance trail)")

    lines.extend(["", "## Beliefs"])
    if beliefs:
        for fact_key, version in beliefs.items():
            val = getattr(version, "value", str(version))
            lines.append(f"- **{r(fact_key, redact)}**: {r(str(val), redact)}")
    else:
        lines.append("- (no beliefs)")

    lines.extend([
        "",
        "---",
        "_Import: `synapse card import <file>`_",
    ])
    return "\n".join(lines)


def _render_html(query: str, pack, beliefs: Dict, redact: str | None) -> str:
    md = _render_markdown(query, pack, beliefs, redact)
    # Convert markdown to simple HTML
    html_body = ""
    for line in md.split("\n"):
        if line.startswith("# "):
            html_body += f"<h1>{_esc(line[2:])}</h1>\n"
        elif line.startswith("## "):
            html_body += f"<h2>{_esc(line[3:])}</h2>\n"
        elif line.startswith("- "):
            html_body += f"<li>{_esc(line[2:])}</li>\n"
        elif line.startswith("_") and line.endswith("_"):
            html_body += f"<p class='meta'>{_esc(line.strip('_'))}</p>\n"
        elif line.strip() == "---":
            html_body += "<hr/>\n"
        elif line.strip():
            html_body += f"<p>{_esc(line)}</p>\n"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Memory Card: {_esc(query)}</title>
<style>
:root {{ --bg:#0d1117; --card:#161b22; --text:#c9d1d9; --accent:#58a6ff; --muted:#8b949e; }}
* {{ box-sizing:border-box; margin:0; padding:0; }}
body {{ background:var(--bg); color:var(--text); font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif; padding:2rem; display:flex; justify-content:center; }}
.card {{ background:var(--card); border:1px solid #30363d; border-radius:12px; max-width:720px; width:100%; padding:2rem; }}
h1 {{ color:var(--accent); font-size:1.5rem; margin-bottom:0.5rem; }}
h2 {{ color:var(--accent); font-size:1.1rem; margin-top:1.5rem; margin-bottom:0.5rem; border-bottom:1px solid #21262d; padding-bottom:0.3rem; }}
p {{ margin:0.5rem 0; line-height:1.6; }}
li {{ margin:0.25rem 0 0.25rem 1.5rem; line-height:1.5; }}
hr {{ border:none; border-top:1px solid #30363d; margin:1.5rem 0; }}
.meta {{ color:var(--muted); font-style:italic; font-size:0.9rem; }}
</style>
</head>
<body>
<div class="card">
{html_body}
</div>
</body>
</html>"""


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ── Public API ────────────────────────────────────────────────────────────────

def share_card(
    synapse_instance,
    query: str,
    budget: int = 1600,
    policy: str = "balanced",
    redact: str | None = None,
    format: str = "markdown",
) -> str:
    """Compile context for *query* and render as a shareable artifact.

    Returns the rendered string (markdown or HTML).
    """
    pack = synapse_instance.compile_context(query=query, budget=budget, policy=policy)
    beliefs = synapse_instance.beliefs() or {}

    # Filter beliefs to those relevant to the query
    query_lower = query.lower()
    relevant_beliefs = {}
    for fact_key, version in beliefs.items():
        if any(tok in fact_key.lower() for tok in query_lower.split()):
            relevant_beliefs[fact_key] = version

    if format == "html":
        return _render_html(query, pack, relevant_beliefs, redact)
    return _render_markdown(query, pack, relevant_beliefs, redact)
